version: "3.9"

services:
  back:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
  front:
    build: ./frontend
    ports:
      - "8050:8050"
    environment:
      - BACKEND_URL=http://back:3000/
    networks:
      - app-network

networks:
  app-network:
